
@startmindmap

<style>
mindmapDiagram {
  .green {
    BackgroundColor lightgreen
  }
  .rose {
    BackgroundColor #FFBBCC
  }
  .your_style_name {
    BackgroundColor lightblue
  }
}
</style>

* CsR <<your_style_name>>

** CsR-1521,Angebotsanfrage Weiterentwicklung DIS-SC-SW (mit UDS) (Important ),Customer_input <<green>>
** CsR-1522,Platzierung Flash Address,Customer Req <<green>>
*** HLR-Partition of the memory
** CsR-1523,Verwendung des BMHD1,Customer Req <<green>>
*** HLR-Use BMHD
** CsR-1524,Freilassung der BMHD0 ,Customer Req  <<green>>
*** HLR-Use BMHD

** CsR-1525,Freilassung  für den Loadercode,Customer Req <<green>>
*** HLR-Partition of the memory

** CsR-1526,Reagierung auf Request auf der UDS Schnittstelle,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence

** CsR-1527,Reagierung auf der TesterPresent,Customer Req <<green>>
** CsR-1528,Reagierung Positive Response,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence

** CsR-1529,Reagierung Negative Response,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence

** CsR-1530,Umsetzung UDS ,Customer Req <<green>>
*** ICD CAN_Tx_ UDS_DIS_SC-CR, ICD CAN_Rx_UDS_Tester_2_DIS_SC-CR <<rose>>

** CsR-1532,Umsetzung des Services,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence

** CsR-1543,UDS Request,Customer Req <<green>>
*** HLR-Configure CAN_Rx Message Identifier_CR

** CsR-1544,UDS Schnittstelle ,Customer_input <<green>>
** CsR-1545,UDS Response,Customer Req <<green>>
*** HLR-Configure CAN Message Identifier_CR, Response Time for UDS Request

** CsR-1546,Sicherer Zustand SHUTOFF durch KL15 ,Customer Req <<green>>
*** HLR-Action: No BR ShutOff Sequence, Action : With BR ShutOff Sequence

** CsR-1547,Sicherer Zustand SHUTOFF durch UDS Befehl ,Customer Req <<green>>
*** HLR-Disable  Safety Mechanism and SMU alarms, Jump to Loader SW, Transit to ShutOff via UDS Request, Configure Window Watchdog, Configure Window Watchdog Trigger

** CsR-1548,Zustände des ICU SC,Customer Req <<green>>

** CsR-1549,Sequenzdiagramm Abschaltsequenz ,Customer Req <<green>>

** CsR-1550,Shutoff ,Customer_input <<green>>

** CsR-1551,Shutoff Trigger ,Customer Req <<green>>
*** HLR-Transit to ShutOff via UDS Request, Action: No BR ShutOff Sequence

** CsR-1552,Anforderung Programming Session ,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence, Use NRC (Negative Response Code) to Response, Transit to ShutOff via UDS Request

** CsR-1553,Shutoffsequenz  ,Customer Req <<green>>
*** HLR-Action : With BR ShutOff Sequence

** CsR-1554,Sequenzdiagramm Shutoffsequenz,Customer Req <<green>>
*** HLR-Action : With BR ShutOff Sequence, Jump to Loader SW, Disable  Safety Mechanism and SMU alarms, Configure Window Watchdog Trigger, Configure Window Watchdog, Disable Functional Watchdog

** CsR-1555,Plausibilisierung der Motorströme (nothing change),Customer Req <<green>>
*** HLR-Use UpDownCounter to monitor MotorCurrents Sum

** CsR-1556,Softwareversionsheader und Datensatzversion ,Customer Req <<green>>
*** HLR-Allocate Memory Address for SWID
*** HLR-Use BMHD
*** HLR-Partition of the memory

** CsR-1557,Übertragung der SW Version und der Datensatznummer,Customer Req <<green>>
*** HLR-Transmit Dataset identifier, Read and Transmit Dataset Number, Read and Transmit SW Version 

** CsR-1558,Erfassung der Spannung +1,0Voffset für Strommessung ,Customer Req <<green>>
*** HLR-Declare integrity violation for +1.0Voffset

** CsR-1559,Filtern der Spannung +1,0Voffset ,Customer Req <<green>>
*** HLR-Filter +1.0Voffset Voltage

** CsR-2091,2 Overview CAN Messages (Intercontroller) update to CsR-1037 ,Customer Req <<green>>
*** HLR-Configure CAN_Rx Message Identifier_CR
*** HLR-Configure CAN Tx Cycle time_CR
*** HLR-Configure CAN Message Identifier_CR
*** ICD CAN_Rx_UDS_Tester_2_DIS_SC-CR <<rose>>
*** ICD CAN_TX_SWID_DIS_SC (Change request) <<rose>>
*** ICD CAN_Tx_ UDS_DIS_SC-CR <<rose>>

** CsR-2092,3.4 SWID_DIS_SC,Customer Req <<green>>
*** HLR-Read and Transmit SW Version
*** HLR-Read and Transmit Dataset Number
*** ICD releaseMaturity <<rose>> 
*** ICD oemSspecific <<rose>> 
*** ICD revisionVariant <<rose>> 
*** ICD hardwareCompatitbility <<rose>> 
*** ICD CAN_TX_SWID_DIS_SC (Change request) <<rose>>
*** ICD datasetVersionNumber <<rose>> 

** CsR-2094,3.5 UDS_DIS_SC - UDS Response Identifier,Customer Req <<green>>
*** HLR-Use NRC (Negative Response Code) to Response
*** ICD-udsResponse <<rose>> 
*** ICD-udsNRC <<rose>>
*** ICD-length Tx <<rose>>
*** ICD-CAN_Tx_ UDS_DIS_SC-CR <<rose>>
*** ICD-udsSidRequest <<rose>>

** CsR-2095,3.6 UDS_DIS_MC - UDS Response Identifier ,Customer Req <<green>>
** CsR-2096,3.7 UDS_Tester_2_DIS_SC - UDS Request Identifier ,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence
*** ICD-sid <<rose>>
*** ICD-subFunction <<rose>> 
*** ICD-CAN_Rx_UDS_Tester_2_DIS_SC-CR <<rose>>
*** ICD-length Rx <<rose>>

** CsR-2097,3.8 UDS_Tester_2_DIS_MC - UDS Request Identifier ,Customer Req <<green>>

** CsR-2099,CR Filterung der Spannung 1Voffset / Up-down-Counter.,Customer Req <<green>>
*** HLR-Use UpDownCounter to monitor MotorCurrents Sum

** CsR-2100,Questions about bootloader and 1VOfsset voltage filter,Customer Req <<green>>
*** HLR-Filter +1.0Voffset Voltage

** CsR-2700,MoM UDS protocol data length,Customer Req <<green>>
*** HLR-Action : UDS Request/Response Sequence

** CsR-2702,Project Release Loader Preparation and Voltage Filter,Customer Req <<green>>
*** HLR-Use NRC (Negative Response Code) to Response

** CsR-2703,DS_IDENTIFICATION_[32],Customer Req <<green>>

** CsR-2699,ONE_VOLT_OFFSET_2MS_FILTER_UNITS,Customer Req <<green>>
*** HLR-Filter +1.0Voffset Voltage
*** ICD-one_volt_offset_2ms_filter_units <<rose>>

** CsR-2704,DS_VERSION_[32],Customer Req <<green>>

@endmindmap  
